<?php

$latest = '7.3';

$php_versions = array(
	'5.2' => 'https://github.com/wp-cli/wp-cli/releases/download/v1.5.1/wp-cli-1.5.1.phar',
	'5.3' => 'https://github.com/wp-cli/wp-cli/releases/download/v1.5.1/wp-cli-1.5.1.phar',
	'5.4' => 'https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar',
	'5.5' => 'https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar',
	'5.6' => 'https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar',
	'7.0' => 'https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar',
	'7.1' => 'https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar',
	'7.2' => 'https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar',
	'7.3' => 'https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar',
);

$php_versions['latest'] = $php_versions[ $latest ];

$generated_warning = <<<EOT
##########################################################################
#
# WARNING: This file was generated by update.php. Do not edit it directly.
#
#
EOT;

$template   = file_get_contents( 'Dockerfile.template' );

foreach ( $php_versions as $version => $download_url ) {
	echo "-----\n$version\n-----\n";
	if ( 'latest' === $version ) {
		$branch_exists = true;
		echo "Checkout master\n";
		echo shell_exec( 'git checkout master' );
	} else {
		echo "Check for remote branch\n";
		$branch_exists = shell_exec( "git ls-remote --heads git@github.com:pento/wordpress-develop-php.git $version-fpm" );
		if ( ! $branch_exists ) {
			echo "Remote branch doesn't exist. Checkout master.\n";
			echo shell_exec( 'git checkout master' );
			echo "Create branch\n";
			echo shell_exec( "git checkout -b $version-fpm" );
			echo "Remove unnecessary files\n";
			echo shell_exec( "git rm Dockerfile.template update.php" );
			echo "Commit file removal\n";
			echo shell_exec( "git commit -m 'Creating a new branch for PHP $version.'" );
		} else {
			echo "Remote branch exists. Check it out.\n";
			echo shell_exec( "git checkout $version-fpm" );
		}
	}

	$dockerfile = $template;

	if ( 'latest' === $version ) {
		$version_tag = 'latest';
	} else {
		$version_tag = "$version-fpm";
	}
	$dockerfile = str_replace( '%%VERSION_TAG%%', $version_tag, $dockerfile );

	$dockerfile = str_replace( '%%GENERATED_WARNING%%', $generated_warning, $dockerfile );

	$dockerfile = str_replace( '%%DOWNLOAD_URL%%', $download_url, $dockerfile );

	$dockerfile = preg_replace( '/%%[^%]+%%/', '', $dockerfile );

	$fh = fopen( 'Dockerfile', 'w' );
	fwrite( $fh, $dockerfile );
	fclose( $fh );

	echo "Add changed files\n";
	echo shell_exec( 'git add -A' );
	echo "Commit changed files\n";
	echo shell_exec( "git commit -m 'Update the image for PHP $version.'" );
	echo "Push changes\n";
	if ( $branch_exists ) {
		echo shell_exec( 'git push' );
	} else {
		echo shell_exec( "git push --set-upstream origin $version-fpm" );
	}
}
